#!/usr/bin/env bash

shopt -s nullglob globstar

action=copy
case $1 in
	--type)
		action=type
		shift
		;;
	--type-and-copy)
		action=typeandcopy
		shift
		;;
esac

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password=$(printf '%s\n' "${password_files[@]}" | dmenu "$@")

[[ -n $password ]] || exit

copy_password () {
	pass show -c "$password" 2>/dev/null
}

type_password () {
	pass show "$password" | head -n 1 | tr -d '\n' |
		xdotool type --clearmodifiers --file -
}

type_username () {
	pass show "$password" | head -n 2 | tail -n +2 | tr -d '\n' |
		xdotool type --clearmodifiers --file -
}

case $action in
	copy)
		copy_password
		;;
	type)
		type_password
		;;
	typeandcopy)
		type_username
		copy_password
		;;
esac
